DROP TYPE profile_type CASCADE;

CREATE TYPE profile_type AS ENUM ( 'EMAIL', 'FIRST_NAME', 'LAST_NAME', 'PHONE', 'STREET', 'CITY', 'STATE', 'ZIP', 'BIRTH_DATE', 'GENDER', 'CAMPUS', 'GRADUATION', 'DORMITORY' );
